DROP TABLE IDENTITIES;
CREATE TABLE IDENTITIES
	(ID INT NOT NULL GENERATED ALWAYS AS IDENTITY 
	(START WITH 1, INCREMENT BY 1), 
	FIRSTNAME VARCHAR(100), 
	LASTNAME VARCHAR(100),
	EMAIL VARCHAR(255),
	BIRTHDATE DATE
	);